### ISSUE TITLE
Cập nhật kế hoạch phân chia công việc nhóm

### ISSUE THREAD

**Issue by KienTrann** [Trung-Rei/kaggle-porto-seguro#1]
Trong link Trello của tụi em, mình thấy có phân chia công việc cho các thành viên, nhưng không thấy ghi khoảng thời gian thực hiện là từ ngày nào đến ngày nào. Tụi em cập nhật thêm để cho rõ hơn nha.

**Comment by Trung-Rei** [comment]
Em hiểu rồi ạ.
